name: Upload File to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  upload-to-cloudshell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          project_id: cicdgithubactions  # Replace with your actual project ID
          credentials_json: ${{ secrets.GCP_OAUTH_TOKEN }}  # Service account JSON key stored in GitHub secrets

      - name: Upload test.txt to Google Cloud Storage
        run: |
          # Ensure gsutil is authenticated with the credentials
          echo "Uploading test.txt to Cloud Storage..."
          gsutil cp test.txt gs://your-bucket-name/test.txt  # Replace with your bucket name

      - name: Confirm upload
        run: |
          gsutil ls gs://your-bucket-name/  # List files in the bucket to confirm upload
